CREATE DATABASE supply_chain;
USE supply_chain;

CREATE TABLE supply_chain_data (
    Type VARCHAR(50),
    Days_for_shipping_real INT,
    Days_for_shipment_scheduled INT,
    Benefit_per_order DECIMAL(10,2),
    Sales_per_customer DECIMAL(10,2),
    Delivery_Status VARCHAR(50),
    Late_delivery_risk INT,
    Category_Id INT,
    Category_Name VARCHAR(100),
    Customer_City VARCHAR(100),
    Customer_Country VARCHAR(100),
    Customer_Email VARCHAR(150),
    Customer_Fname VARCHAR(100),
    Customer_Id INT,
    Customer_Lname VARCHAR(100),
    Customer_Password VARCHAR(100),
    Customer_Segment VARCHAR(50),
    Customer_State VARCHAR(50),
    Customer_Street VARCHAR(150),
    Customer_Zipcode VARCHAR(50),
    Department_Id INT,
    Department_Name VARCHAR(100),
    Latitude DECIMAL(10,6),
    Longitude DECIMAL(10,6),
    Market VARCHAR(50),
    Order_City VARCHAR(100),
    Order_Country VARCHAR(100),
    Order_Customer_Id INT,
    order_date VARCHAR(100), -- Date string format mein load hoga pehle
    Order_Id INT,
    Order_Item_Cardprod_Id INT,
    Order_Item_Discount DECIMAL(10,2),
    Order_Item_Discount_Rate DECIMAL(5,2),
    Order_Item_Id INT,
    Order_Item_Product_Price DECIMAL(10,2),
    Order_Item_Profit_Ratio DECIMAL(5,2),
    Order_Item_Quantity INT,
    Sales DECIMAL(10,2),
    Order_Item_Total DECIMAL(10,2),
    Order_Profit_Per_Order DECIMAL(10,2),
    Order_Region VARCHAR(100),
    Order_State VARCHAR(100),
    Order_Status VARCHAR(50),
    Order_Zipcode VARCHAR(50),
    Product_Card_Id INT,
    Product_Category_Id INT,
    Product_Description VARCHAR(255),
    Product_Image VARCHAR(255),
    Product_Name VARCHAR(150),
    Product_Price DECIMAL(10,2),
    Product_Status INT,
    shipping_date_DateOrders VARCHAR(100), -- Date string format mein load hoga pehle
    Shipping_Mode VARCHAR(50)
);
